### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by mjako78** [platanus/job_notifier#5]
Seems that this gem require Rails 4.2 branch.
Is there any planning to support Rails 5?
Can I help in some way?

**Comment by agustinf** [comment]
We haven't needed working with Rails 5 and this gem, but of you made a Pull Request, it would surely be considered and eventually merged!! Thanks!

**Comment by mjako78** [comment]
Ok. I see what I am capable of doing. 
I start cloning the repo and working on it.

**Comment by ldlsegovia** [comment]
The gem should be working with Rails 5 since [Release 1.2.4](https://github.com/platanus/job_notifier/releases/tag/v1.2.4)
